package macos

import (
	"context"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/modullar/blade-runner/internal/diag"
	"github.com/modullar/blade-runner/internal/execx"
	"github.com/modullar/blade-runner/internal/platform"
)

var update = flag.Bool("update", false, "rewrite golden files")

var ctx = context.Background()

func goldenSpec() platform.Spec {
	return platform.Spec{
		RunnerName: "mac-mini-1",
		RunnerDir:  "/Users/dev/.bladerunner/runners/mac-mini-1/runner",
		LogDir:     "/Users/dev/.bladerunner/runners/mac-mini-1/logs",
		Home:       "/Users/dev",
	}
}

func TestRenderMatchesGolden(t *testing.T) {
	p := &Platform{UID: 501, Home: "/Users/dev"}
	got, err := p.Render(goldenSpec())
	if err != nil {
		t.Fatal(err)
	}
	golden := filepath.Join("testdata", "runner.plist.golden")
	if *update {
		if err := os.WriteFile(golden, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(want) {
		t.Errorf("plist differs from %s (run with -update if intended):\n%s", golden, got)
	}
	if !strings.Contains(string(got), "GENERATED by bladerunner - do not edit by hand") {
		t.Error("generated plist must carry the do-not-edit header")
	}
}

func TestRenderEscapesXMLInValues(t *testing.T) {
	s := goldenSpec()
	s.RunnerDir = "/Users/a&b/<x>/runner"
	out, err := (&Platform{}).Render(s)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(out), "a&b") || !strings.Contains(string(out), "a&amp;b") || strings.Contains(string(out), "<x>") {
		t.Errorf("values must be XML-escaped:\n%s", out)
	}
}

// launchctl is a small stateful stand-in for launchd.
type launchctl struct {
	loaded, running bool
	uid             string
	mutations       []string
	// unloadPolls makes bootout asynchronous like the real launchd: the service stays
	// loaded for that many `print` queries after bootout returns.
	unloadPolls, pending int
}

func (l *launchctl) handle(c execx.Cmd) (execx.Result, error) {
	if c.Name != "launchctl" {
		return execx.Result{}, nil
	}
	switch c.Args[0] {
	case "print":
		if c.Args[1] == "gui/"+l.uid { // the domain itself: a GUI session exists
			return execx.Result{Stdout: "domain\n"}, nil
		}
		if l.pending > 0 {
			l.pending--
			if l.pending == 0 {
				l.loaded, l.running = false, false
			}
		}
		if !l.loaded {
			return execx.Fail("launchctl", 113, "Could not find service")
		}
		state := "waiting"
		if l.running {
			state = "running"
		}
		return execx.Result{Stdout: "service = x\n\tstate = " + state + "\n"}, nil
	case "bootstrap":
		l.mutations = append(l.mutations, "bootstrap")
		l.loaded, l.running = true, true
	case "bootout":
		l.mutations = append(l.mutations, "bootout")
		if l.unloadPolls > 0 {
			l.pending = l.unloadPolls
		} else {
			l.loaded, l.running = false, false
		}
	case "kickstart":
		l.mutations = append(l.mutations, "kickstart")
		l.running = true
	}
	return execx.Result{}, nil
}

func newPlatform(t *testing.T) (*Platform, *launchctl, platform.Spec) {
	t.Helper()
	home := t.TempDir()
	l := &launchctl{uid: "501"}
	p := &Platform{Exec: &execx.Fake{Handler: l.handle}, UID: 501, Home: home}
	s := goldenSpec()
	s.Home = home
	s.LogDir = filepath.Join(home, "logs")
	return p, l, s
}

func TestInstallStartStatusLifecycle(t *testing.T) {
	p, l, s := newPlatform(t)

	st, err := p.Status(ctx, s)
	if err != nil || st.Installed || st.Running {
		t.Fatalf("fresh machine: %+v, %v", st, err)
	}
	if err := p.Install(ctx, s); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(p.DefinitionPath(s)); err != nil {
		t.Fatalf("plist not written: %v", err)
	}
	if !strings.HasSuffix(p.DefinitionPath(s), "/Library/LaunchAgents/dev.bladerunner.runner.mac-mini-1.plist") {
		t.Errorf("plist path = %s", p.DefinitionPath(s))
	}
	if len(l.mutations) != 0 {
		t.Errorf("Install must not start the service, launchctl saw %v", l.mutations)
	}
	if st, _ = p.Status(ctx, s); !st.Installed || !st.Current || st.Running {
		t.Errorf("after Install: %+v", st)
	}

	if err := p.Start(ctx, s); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(l.mutations, []string{"bootstrap"}) {
		t.Errorf("Start mutations = %v, want [bootstrap]", l.mutations)
	}
	if st, _ = p.Status(ctx, s); !st.Running || !strings.Contains(st.Detail, "running") {
		t.Errorf("after Start: %+v", st)
	}

	l.mutations = nil
	if err := p.Start(ctx, s); err != nil || len(l.mutations) != 0 {
		t.Errorf("Start on a running service must do nothing: %v, %v", err, l.mutations)
	}
	if err := p.Install(ctx, s); err != nil || len(l.mutations) != 0 {
		t.Errorf("re-Install of an unchanged definition must do nothing: %v, %v", err, l.mutations)
	}
}

func TestStartKicksAServiceThatIsLoadedButNotRunning(t *testing.T) {
	p, l, s := newPlatform(t)
	if err := p.Install(ctx, s); err != nil {
		t.Fatal(err)
	}
	l.loaded, l.running = true, false
	if err := p.Start(ctx, s); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(l.mutations, []string{"kickstart"}) {
		t.Errorf("mutations = %v, want [kickstart]", l.mutations)
	}
}

func TestChangedDefinitionUnloadsTheOldOneSoStartRebootstraps(t *testing.T) {
	p, l, s := newPlatform(t)
	if err := p.Install(ctx, s); err != nil {
		t.Fatal(err)
	}
	if err := p.Start(ctx, s); err != nil {
		t.Fatal(err)
	}
	l.mutations = nil

	s.RunnerDir = filepath.Join(s.Home, "moved", "runner")
	if st, _ := p.Status(ctx, s); st.Current {
		t.Fatal("Status must report a stale definition as not current")
	}
	if err := p.Install(ctx, s); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(l.mutations, []string{"bootout"}) {
		t.Errorf("Install of a changed definition: %v, want [bootout]", l.mutations)
	}
	if err := p.Start(ctx, s); err != nil {
		t.Fatal(err)
	}
	if st, _ := p.Status(ctx, s); !st.Running || !st.Current {
		t.Errorf("after restart: %+v", st)
	}
}

// fakeClock lets the unload wait run without real sleeping.
type fakeClock struct{ t time.Time }

func (c *fakeClock) now() time.Time        { return c.t }
func (c *fakeClock) sleep(d time.Duration) { c.t = c.t.Add(d) }

func TestStopWaitsUntilLaunchdHasLetGo(t *testing.T) {
	p, l, s := newPlatform(t)
	clock := &fakeClock{t: time.Unix(0, 0)}
	p.Now, p.Sleep = clock.now, clock.sleep
	_ = p.Install(ctx, s)
	_ = p.Start(ctx, s)

	l.unloadPolls = 4 // launchd keeps the service loaded for a few queries after bootout
	if err := p.Stop(ctx, s); err != nil {
		t.Fatal(err)
	}
	if l.loaded {
		t.Error("Stop returned while the service was still loaded: a following bootstrap would fail with Input/output error")
	}
	if clock.t.Sub(time.Unix(0, 0)) == 0 {
		t.Error("Stop did not wait at all")
	}
}

func TestStopGivesUpIfLaunchdNeverLetsGo(t *testing.T) {
	p, l, s := newPlatform(t)
	clock := &fakeClock{t: time.Unix(0, 0)}
	p.Now, p.Sleep, p.UnloadWait = clock.now, clock.sleep, 5*time.Second
	_ = p.Install(ctx, s)
	_ = p.Start(ctx, s)
	l.unloadPolls = 1 << 30
	err := p.Stop(ctx, s)
	if diag.CodeOf(err) != diag.CodeServiceInstall || !strings.Contains(err.Error(), "still loaded") {
		t.Errorf("err = %v, want BR-E050 saying the service is still loaded", err)
	}
	if waited := clock.t.Sub(time.Unix(0, 0)); waited < 5*time.Second || waited > 7*time.Second {
		t.Errorf("waited %v, want about the 5s limit", waited)
	}
}

func TestChangedDefinitionWaitsForUnloadBeforeStartBootstraps(t *testing.T) {
	p, l, s := newPlatform(t)
	clock := &fakeClock{t: time.Unix(0, 0)}
	p.Now, p.Sleep = clock.now, clock.sleep
	_ = p.Install(ctx, s)
	_ = p.Start(ctx, s)
	l.unloadPolls = 3
	s.RunnerDir = filepath.Join(s.Home, "moved", "runner")
	if err := p.Install(ctx, s); err != nil {
		t.Fatal(err)
	}
	if l.loaded {
		t.Fatal("Install returned with the old definition still loaded")
	}
	if err := p.Start(ctx, s); err != nil {
		t.Fatalf("Start right after a changed Install: %v", err)
	}
}

func TestStopAndUninstall(t *testing.T) {
	p, l, s := newPlatform(t)
	if err := p.Stop(ctx, s); err != nil || len(l.mutations) != 0 {
		t.Errorf("Stop when not loaded must be a no-op: %v, %v", err, l.mutations)
	}
	_ = p.Install(ctx, s)
	_ = p.Start(ctx, s)
	if err := p.Uninstall(ctx, s); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(p.DefinitionPath(s)); !os.IsNotExist(err) {
		t.Error("plist still present after Uninstall")
	}
	if l.loaded {
		t.Error("service still loaded after Uninstall")
	}
	if err := p.Uninstall(ctx, s); err != nil {
		t.Errorf("Uninstall twice must succeed: %v", err)
	}
}

func TestLaunchctlFailuresAreDiagnosed(t *testing.T) {
	p, _, s := newPlatform(t)
	p.Exec = &execx.Fake{Handler: func(c execx.Cmd) (execx.Result, error) {
		if c.Args[0] == "print" {
			return execx.Fail("launchctl", 113, "not loaded")
		}
		return execx.Fail("launchctl", 5, "Bootstrap failed: 5: Input/output error")
	}}
	_ = p.Install(ctx, s)
	err := p.Start(ctx, s)
	if diag.CodeOf(err) != diag.CodeServiceInstall || !strings.Contains(err.Error(), "Bootstrap failed") {
		t.Errorf("err = %v, want BR-E050 carrying launchctl's message", err)
	}
}

func TestPrereqs(t *testing.T) {
	good := &launchctl{uid: "501"}
	f := &execx.Fake{Tools: map[string]bool{"git": true, "launchctl": true}, Handler: good.handle}
	for _, pr := range (&Platform{Exec: f, UID: 501}).CheckPrereqs(ctx) {
		if !pr.OK {
			t.Errorf("prereq %q should pass: %+v", pr.Name, pr)
		}
	}

	bad := &execx.Fake{Handler: func(c execx.Cmd) (execx.Result, error) { return execx.Fail(c.Name, 1, "no") }}
	got := map[string]platform.Prereq{}
	for _, pr := range (&Platform{Exec: bad, UID: 501}).CheckPrereqs(ctx) {
		got[pr.Name] = pr
	}
	for _, name := range []string{"git", "launchctl", "Xcode Command Line Tools", "GUI login session"} {
		pr, ok := got[name]
		if !ok || pr.OK || pr.Fix == "" {
			t.Errorf("prereq %q on a bare machine = %+v, want a failure with a fix", name, pr)
		}
	}
}

func TestLogsTailsTheLogFile(t *testing.T) {
	p, _, s := newPlatform(t)
	f := &execx.Fake{Handler: func(c execx.Cmd) (execx.Result, error) { return execx.Result{Stdout: "line1\n"}, nil }}
	p.Exec = f
	var out strings.Builder
	if err := p.Logs(ctx, s, true, &out); err != nil {
		t.Fatal(err)
	}
	if out.String() != "line1\n" {
		t.Errorf("output = %q", out.String())
	}
	if want := "[tail -n 200 -f " + filepath.Join(s.LogDir, "runner.log") + "]"; f.Line(0) != want {
		t.Errorf("command = %s, want %s", f.Line(0), want)
	}
}
