package install

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/modullar/blade-runner/internal/core"
	"github.com/modullar/blade-runner/internal/diag"
	"github.com/modullar/blade-runner/internal/hook"
)

// The job hook is what actually keeps other people's code off this machine: the runner runs it
// before every job, and a non-zero exit fails the job before any step starts. Its policy lives
// here, on the owner's disk, where no pull request can edit it. See internal/hook.

// hookEnvVar is the runner setting that names the job-started hook. It is read from the `.env`
// file in the runner directory at startup (assumption, unverified until BR-0).
const hookEnvVar = "ACTIONS_RUNNER_HOOK_JOB_STARTED"

const scriptHeader = "#!/bin/sh\n# GENERATED by bladerunner - do not edit by hand. Source: bladerunner.yaml\n" +
	"# Runs before every job on this runner and refuses jobs from anyone you do not trust.\n"

func (e *Env) hookScriptPath() string { return filepath.Join(e.Layout.HooksDir(), "job-started.sh") }
func (e *Env) hookPolicyPath() string { return filepath.Join(e.Layout.HooksDir(), "policy.json") }
func (e *Env) runnerEnvPath() string  { return filepath.Join(e.Layout.RunnerDir(), ".env") }

// HookPolicy is the policy derived from the config.
func (e *Env) HookPolicy() hook.Policy {
	r := e.Cfg.Runner
	return hook.Policy{
		Version: 1, Scope: r.Scope, Repository: r.Repository, Organization: r.Organization,
		TrustedActors: r.TrustedActors,
	}
}

// hookFiles renders the script and the policy file.
func (e *Env) hookFiles() (script, policy []byte, err error) {
	if e.BinaryPath == "" {
		return nil, nil, diag.New(diag.CodeJobHook, "cannot tell where the bladerunner program is",
			"the job hook calls the program back, so it needs its path", "run bladerunner by its full path")
	}
	for _, p := range []string{e.BinaryPath, e.hookPolicyPath()} {
		if strings.ContainsAny(p, "'\n") {
			return nil, nil, diag.New(diag.CodeJobHook, fmt.Sprintf("path %q cannot be used in the job hook script", p),
				"it contains a quote or a newline", "move the program or BLADERUNNER_HOME to a path without them")
		}
	}
	script = []byte(scriptHeader + fmt.Sprintf("exec '%s' hook job-started --policy '%s'\n", e.BinaryPath, e.hookPolicyPath()))
	policy, err = json.MarshalIndent(e.HookPolicy(), "", "  ")
	return script, append(policy, '\n'), err
}

// HookProblem reports what is wrong with the installed job hook, or "" when it is complete.
func (e *Env) HookProblem() (string, error) { return e.hookState() }

// hookState reports what is wrong with the installed hook, or "" when it is complete.
func (e *Env) hookState() (problem string, err error) {
	script, policy, err := e.hookFiles()
	if err != nil {
		return "", err
	}
	check := func(path string, want []byte, what string) string {
		got, rerr := os.ReadFile(path)
		switch {
		case rerr != nil:
			return what + " is missing"
		case !bytes.Equal(got, want):
			return what + " is out of date"
		}
		return ""
	}
	if p := check(e.hookScriptPath(), script, "the job hook script"); p != "" {
		return p, nil
	}
	if info, _ := os.Stat(e.hookScriptPath()); info == nil || info.Mode().Perm()&0o100 == 0 {
		return "the job hook script is not executable", nil
	}
	if p := check(e.hookPolicyPath(), policy, "the job policy"); p != "" {
		return p, nil
	}
	if _, serr := os.Stat(e.BinaryPath); serr != nil {
		return "the bladerunner program the hook calls (" + e.BinaryPath + ") no longer exists, so every job would be refused", nil
	}
	env, _ := os.ReadFile(e.runnerEnvPath())
	if !hasEnvLine(string(env), hookEnvVar, e.hookScriptPath()) {
		return "the runner is not told to use the hook (" + hookEnvVar + " is not set in its .env)", nil
	}
	return "", nil
}

func hasEnvLine(env, key, value string) bool {
	for _, l := range strings.Split(env, "\n") {
		if strings.TrimSpace(l) == key+"="+value {
			return true
		}
	}
	return false
}

// withEnvLine sets key=value in an .env file's text, keeping every other line.
func withEnvLine(env, key, value string) string {
	var out []string
	for _, l := range strings.Split(strings.TrimRight(env, "\n"), "\n") {
		if l != "" && !strings.HasPrefix(strings.TrimSpace(l), key+"=") {
			out = append(out, l)
		}
	}
	return strings.Join(append(out, key+"="+value), "\n") + "\n"
}

type jobHook struct{ e *Env }

func (*jobHook) ID() string { return "job-hook" }
func (*jobHook) Describe() string {
	return "install the job hook that refuses jobs from anyone you do not trust"
}

func (s *jobHook) Check(context.Context) (core.Status, error) {
	if _, err := os.Stat(filepath.Join(s.e.Layout.RunnerDir(), "config.sh")); err != nil {
		return core.Status{Reason: "runner binary not installed yet"}, nil
	}
	problem, err := s.e.hookState()
	if err != nil {
		return core.Status{}, err
	}
	if problem != "" {
		return core.Status{Reason: problem}, nil
	}
	return core.Status{Done: true, Reason: "jobs are checked against the policy before they start"}, nil
}

func (s *jobHook) Apply(ctx context.Context) error {
	e := s.e
	script, policy, err := e.hookFiles()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(e.Layout.HooksDir(), 0o700); err != nil {
		return diag.Wrap(err, diag.CodeJobHook, "cannot create the hooks directory", "the path is not writable", "check "+e.Layout.HooksDir())
	}
	if err := writeFileAtomic(e.hookScriptPath(), script, 0o700); err != nil {
		return diag.Wrap(err, diag.CodeJobHook, "cannot write the job hook script", "the disk is full or read-only", "check "+e.Layout.HooksDir())
	}
	if err := writeFileAtomic(e.hookPolicyPath(), policy, 0o600); err != nil {
		return diag.Wrap(err, diag.CodeJobHook, "cannot write the job policy", "the disk is full or read-only", "check "+e.Layout.HooksDir())
	}
	old, _ := os.ReadFile(e.runnerEnvPath())
	if err := writeFileAtomic(e.runnerEnvPath(), []byte(withEnvLine(string(old), hookEnvVar, e.hookScriptPath())), 0o600); err != nil {
		return diag.Wrap(err, diag.CodeJobHook, "cannot update the runner's .env", "the runner directory is not writable", "check "+e.Layout.RunnerDir())
	}
	// The runner reads its .env when it starts: a runner that is already running would keep
	// accepting jobs without the hook. Stop it; the next step starts it again.
	if st, err := e.Platform.Status(ctx, e.Spec()); err == nil && st.Running {
		return e.Platform.Stop(ctx, e.Spec())
	}
	return nil
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
