package install_test

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/modullar/blade-runner/internal/diag"
	"github.com/modullar/blade-runner/internal/hook"
	"github.com/modullar/blade-runner/internal/testrig"
)

// runHook executes the generated hook script exactly as the runner would: a real process, with
// the job's environment. It returns the exit code and the combined output.
func runHook(t *testing.T, r *testrig.Rig, env map[string]string) (int, string) {
	t.Helper()
	script := filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh")
	cmd := exec.Command(script)
	cmd.Env = []string{"PATH=" + os.Getenv("PATH"), "HOME=" + r.UserHome}
	for k, v := range env {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
	var out bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &out
	err := cmd.Run()
	if err == nil {
		return 0, out.String()
	}
	if ee, ok := err.(*exec.ExitError); ok {
		return ee.ExitCode(), out.String()
	}
	t.Fatalf("cannot run the hook script: %v", err)
	return -1, ""
}

func job(actor, event string, extra ...string) map[string]string {
	m := map[string]string{"GITHUB_REPOSITORY": "acme/widgets", "GITHUB_ACTOR": actor, "GITHUB_EVENT_NAME": event}
	for i := 0; i < len(extra); i += 2 {
		m[extra[i]] = extra[i+1]
	}
	return m
}

func eventFile(t *testing.T, body string) string {
	p := filepath.Join(t.TempDir(), "event.json")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

const (
	sameRepoPR = `{"pull_request":{"head":{"repo":{"full_name":"acme/widgets"}}}}`
	forkPR     = `{"pull_request":{"head":{"repo":{"full_name":"mallory/widgets"}}}}`
)

func applied(t *testing.T) *testrig.Rig {
	t.Helper()
	r := testrig.New(t, testrig.BaseConfig)
	if _, _, err := r.Apply(); err != nil {
		t.Fatal(err)
	}
	return r
}

func TestApplyInstallsTheHookFilesAndTellsTheRunner(t *testing.T) {
	r := applied(t)
	script, err := os.ReadFile(filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"#!/bin/sh", "GENERATED by bladerunner - do not edit by hand", "exec '" + r.Env.BinaryPath + "' hook job-started --policy '"} {
		if !strings.Contains(string(script), want) {
			t.Errorf("script missing %q:\n%s", want, script)
		}
	}
	if info, _ := os.Stat(filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh")); info.Mode().Perm() != 0o700 {
		t.Errorf("script mode = %v, want 0700", info.Mode().Perm())
	}
	var p hook.Policy
	raw, _ := os.ReadFile(filepath.Join(r.Env.Layout.HooksDir(), "policy.json"))
	if err := json.Unmarshal(raw, &p); err != nil || p.Repository != "acme/widgets" || !reflect.DeepEqual(p.TrustedActors, []string{"acme"}) {
		t.Errorf("policy = %+v, %v", p, err)
	}
	env, _ := os.ReadFile(filepath.Join(r.Env.Layout.RunnerDir(), ".env"))
	if want := "ACTIONS_RUNNER_HOOK_JOB_STARTED=" + filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh"); !strings.Contains(string(env), want) {
		t.Errorf(".env = %q, want it to contain %q", env, want)
	}
}

// The end-to-end proof of the security requirement: config -> apply -> files on disk -> the
// real program, run the way the runner runs it, deciding real jobs.
func TestTheInstalledHookLetsTheOwnerInAndKeepsEveryoneElseOut(t *testing.T) {
	r := applied(t)
	sameRepo, fork := eventFile(t, sameRepoPR), eventFile(t, forkPR)

	allowed := map[string]map[string]string{
		"my push":                  job("acme", "push"),
		"my manual run":            job("acme", "workflow_dispatch"),
		"my pull request":          job("acme", "pull_request", "GITHUB_EVENT_PATH", sameRepo),
		"my re-run of my own push": job("acme", "push", "GITHUB_TRIGGERING_ACTOR", "acme"),
	}
	for name, env := range allowed {
		if code, out := runHook(t, r, env); code != 0 || !strings.Contains(out, "allowed") {
			t.Errorf("%s: exit %d, output %q, want allowed", name, code, out)
		}
	}

	refused := map[string]struct {
		env  map[string]string
		want string
	}{
		"a stranger's fork pull request":           {job("mallory", "pull_request", "GITHUB_EVENT_PATH", fork), "not a trusted actor"},
		"a stranger whose workflow dropped the if": {job("mallory", "push"), "not a trusted actor"},
		"another collaborator's push":              {job("alice", "push"), "not a trusted actor"},
		"me, updating a stranger's fork branch":    {job("acme", "pull_request", "GITHUB_EVENT_PATH", fork), "comes from mallory/widgets"},
		"a stranger re-running my job":             {job("acme", "push", "GITHUB_TRIGGERING_ACTOR", "mallory"), "triggered this run"},
		"someone else's repository":                {job("acme", "push", "GITHUB_REPOSITORY", "mallory/widgets"), "runner is for acme/widgets"},
		"an issue comment":                         {job("acme", "issue_comment"), "outside your control"},
		"a pull request with no payload":           {job("acme", "pull_request"), "without an event payload"},
		"a job that says nothing about itself":     {map[string]string{}, "did not say"},
	}
	for name, tc := range refused {
		code, out := runHook(t, r, tc.env)
		if code == 0 {
			t.Errorf("%s: was ALLOWED (%s)", name, out)
			continue
		}
		if !strings.Contains(out, "REFUSED") || !strings.Contains(out, tc.want) {
			t.Errorf("%s: output %q should say REFUSED and mention %q", name, out, tc.want)
		}
	}
}

func TestTheHookFailsClosedWhenItsPolicyIsGoneOrBroken(t *testing.T) {
	r := applied(t)
	policy := filepath.Join(r.Env.Layout.HooksDir(), "policy.json")
	ownerPush := job("acme", "push")

	for name, content := range map[string]string{"corrupt": "{ not json", "empty actors": `{"version":1,"scope":"repo","repository":"acme/widgets","trusted_actors":[]}`} {
		if err := os.WriteFile(policy, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		if code, out := runHook(t, r, ownerPush); code == 0 {
			t.Errorf("%s policy: even the owner's job was allowed (%s): a broken policy must refuse everything", name, out)
		}
	}
	if err := os.Remove(policy); err != nil {
		t.Fatal(err)
	}
	if code, _ := runHook(t, r, ownerPush); code == 0 {
		t.Error("a missing policy file must refuse every job")
	}
}

func TestTheHookFailsClosedWhenTheProgramMovedAway(t *testing.T) {
	r := applied(t)
	script := filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh")
	data, _ := os.ReadFile(script)
	broken := strings.Replace(string(data), r.Env.BinaryPath, filepath.Join(t.TempDir(), "gone"), 1)
	if err := os.WriteFile(script, []byte(broken), 0o700); err != nil {
		t.Fatal(err)
	}
	if code, _ := runHook(t, r, job("acme", "push")); code == 0 {
		t.Error("with the program gone the hook must refuse, not shrug")
	}
}

func TestApplyRepairsATamperedHookAndRestartsTheRunner(t *testing.T) {
	for name, tamper := range map[string]func(r *testrig.Rig){
		"policy widened to a stranger": func(r *testrig.Rig) {
			p := filepath.Join(r.Env.Layout.HooksDir(), "policy.json")
			_ = os.WriteFile(p, []byte(`{"version":1,"scope":"repo","repository":"acme/widgets","trusted_actors":["acme","mallory"]}`), 0o600)
		},
		"script replaced by exit 0": func(r *testrig.Rig) {
			_ = os.WriteFile(filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh"), []byte("#!/bin/sh\nexit 0\n"), 0o700)
		},
		"env line removed": func(r *testrig.Rig) {
			_ = os.WriteFile(filepath.Join(r.Env.Layout.RunnerDir(), ".env"), nil, 0o600)
		},
		"script made non-executable": func(r *testrig.Rig) {
			_ = os.Chmod(filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh"), 0o600)
		},
		"hooks directory deleted": func(r *testrig.Rig) { _ = os.RemoveAll(r.Env.Layout.HooksDir()) },
	} {
		t.Run(name, func(t *testing.T) {
			r := applied(t)
			tamper(r)
			stops := r.Plat.Stops
			changed, _, err := r.Apply()
			if err != nil {
				t.Fatal(err)
			}
			if want := []string{"job-hook", "service-running"}; !reflect.DeepEqual(changed, want) {
				t.Errorf("changed = %v, want %v (a running runner must be restarted to pick the hook up)", changed, want)
			}
			if r.Plat.Stops != stops+1 {
				t.Errorf("the runner was stopped %d times, want exactly once", r.Plat.Stops-stops)
			}
			if code, _ := runHook(t, r, job("mallory", "push")); code == 0 {
				t.Error("after repair a stranger is still allowed")
			}
			if code, _ := runHook(t, r, job("acme", "push")); code != 0 {
				t.Error("after repair the owner is refused")
			}
		})
	}
}

func TestEditingTrustedActorsUpdatesTheHookPolicy(t *testing.T) {
	r := applied(t)
	if code, _ := runHook(t, r, job("alice", "push")); code == 0 {
		t.Fatal("alice is not trusted yet")
	}
	r.Env.Cfg.Runner.TrustedActors = []string{"acme", "alice"}
	changed, _, err := r.Apply()
	if err != nil || !reflect.DeepEqual(changed, []string{"job-hook", "service-running"}) {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	if code, out := runHook(t, r, job("alice", "push")); code != 0 {
		t.Errorf("alice should be trusted now: %s", out)
	}
}

func TestExistingEnvLinesAreKept(t *testing.T) {
	r := testrig.New(t, testrig.BaseConfig)
	// apply once to get the runner directory, then add lines the runner itself wrote
	if _, _, err := r.Apply(); err != nil {
		t.Fatal(err)
	}
	env := filepath.Join(r.Env.Layout.RunnerDir(), ".env")
	_ = os.WriteFile(env, []byte("LANG=en_US.UTF-8\nACTIONS_RUNNER_HOOK_JOB_STARTED=/stale/path.sh\nPATH=/custom/bin\n"), 0o600)
	if _, _, err := r.Apply(); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(env)
	for _, want := range []string{"LANG=en_US.UTF-8", "PATH=/custom/bin", "ACTIONS_RUNNER_HOOK_JOB_STARTED=" + filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh")} {
		if !strings.Contains(string(got), want) {
			t.Errorf(".env lost or missed %q:\n%s", want, got)
		}
	}
	if strings.Contains(string(got), "/stale/path.sh") || strings.Count(string(got), "ACTIONS_RUNNER_HOOK_JOB_STARTED=") != 1 {
		t.Errorf("the stale hook line must be replaced, not duplicated:\n%s", got)
	}
}

func TestHookNeedsAKnownProgramPath(t *testing.T) {
	r := testrig.New(t, testrig.BaseConfig)
	r.Env.BinaryPath = ""
	_, _, err := r.Apply()
	if diag.CodeOf(err) != diag.CodeJobHook {
		t.Errorf("err = %v, want BR-E065", err)
	}
	r.Env.BinaryPath = "/tmp/it's a trap/bladerunner"
	if _, _, err := r.Apply(); diag.CodeOf(err) != diag.CodeJobHook {
		t.Errorf("a quote in the program path would break the script: err = %v", err)
	}
}

func TestRemoveDeletesTheHook(t *testing.T) {
	r := applied(t)
	if _, err := r.Remove(); err != nil {
		t.Fatal(err)
	}
	if left := r.Leftovers(); len(left) != 0 {
		t.Errorf("remove left: %v", left)
	}
}

// copyBinary gives the rig its own copy of the program, so a test can move or delete it.
func copyBinary(t *testing.T, r *testrig.Rig) string {
	t.Helper()
	data, err := os.ReadFile(testrig.Binary(t))
	if err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(t.TempDir(), "bladerunner")
	if err := os.WriteFile(p, data, 0o755); err != nil {
		t.Fatal(err)
	}
	r.Env.BinaryPath = p
	return p
}

func TestADeletedProgramIsDetectedAndRepairedByMovingIt(t *testing.T) {
	r := testrig.New(t, testrig.BaseConfig)
	bin := copyBinary(t, r)
	if _, _, err := r.Apply(); err != nil {
		t.Fatal(err)
	}
	if problem, err := r.Env.HookProblem(); err != nil || problem != "" {
		t.Fatalf("a fresh install has a problem: %q %v", problem, err)
	}

	if err := os.Remove(bin); err != nil {
		t.Fatal(err)
	}
	problem, err := r.Env.HookProblem()
	if err != nil || !strings.Contains(problem, "no longer exists") || !strings.Contains(problem, "every job would be refused") {
		t.Fatalf("problem = %q, %v: a deleted program must be reported", problem, err)
	}
	// Re-running apply from the program's new location rewrites the script to point at it.
	newBin := copyBinary(t, r)
	changed, _, err := r.Apply()
	if err != nil || !reflect.DeepEqual(changed, []string{"job-hook", "service-running"}) {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	script, _ := os.ReadFile(filepath.Join(r.Env.Layout.HooksDir(), "job-started.sh"))
	if !strings.Contains(string(script), newBin) || strings.Contains(string(script), bin) {
		t.Errorf("the script should call the program's new path:\n%s", script)
	}
	if code, _ := runHook(t, r, job("acme", "push")); code != 0 {
		t.Error("after the repair the owner's job must run")
	}
}
