package templates

import (
	"io/fs"
	"strings"
	"testing"
)

// Every generated file must say it is generated and must not be hand-edited (spec section 0).
func TestEveryTemplateCarriesTheGeneratedHeader(t *testing.T) {
	entries, err := fs.ReadDir(FS, ".")
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) == 0 {
		t.Fatal("no templates embedded")
	}
	for _, e := range entries {
		data, err := fs.ReadFile(FS, e.Name())
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), "GENERATED by bladerunner - do not edit by hand") {
			t.Errorf("%s lacks the generated-file header", e.Name())
		}
	}
}
