package linux

import (
	"context"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/modullar/blade-runner/internal/diag"
	"github.com/modullar/blade-runner/internal/execx"
	"github.com/modullar/blade-runner/internal/platform"
)

var update = flag.Bool("update", false, "rewrite golden files")

var ctx = context.Background()

func goldenSpec() platform.Spec {
	return platform.Spec{
		RunnerName: "build-box",
		RunnerDir:  "/home/dev/.bladerunner/runners/build-box/runner",
		LogDir:     "/home/dev/.bladerunner/runners/build-box/logs",
		Home:       "/home/dev",
	}
}

func TestRenderMatchesGolden(t *testing.T) {
	got, err := (&Platform{}).Render(goldenSpec())
	if err != nil {
		t.Fatal(err)
	}
	golden := filepath.Join("testdata", "runner.service.golden")
	if *update {
		if err := os.WriteFile(golden, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(want) {
		t.Errorf("unit differs from %s (run with -update if intended):\n%s", golden, got)
	}
	if !strings.HasPrefix(string(got), "# GENERATED by bladerunner - do not edit by hand") {
		t.Error("generated unit must start with the do-not-edit header")
	}
}

func TestRenderRefusesPathsSystemdWouldMisread(t *testing.T) {
	for _, bad := range []string{"/home/a b/runner", "/home/a%h/runner", "/home/$x/runner", `/home/"q"/runner`} {
		s := goldenSpec()
		s.RunnerDir = bad
		if _, err := (&Platform{}).Render(s); diag.CodeOf(err) != diag.CodeServiceInstall {
			t.Errorf("RunnerDir %q: err = %v, want BR-E050", bad, err)
		}
	}
}

// systemd is a small stateful stand-in for systemctl --user and loginctl.
type systemd struct {
	enabled, active, linger bool
	lingerAllowed           bool
	calls                   []string
}

func (s *systemd) handle(c execx.Cmd) (execx.Result, error) {
	switch c.Name {
	case "systemctl":
		args := c.Args[1:] // drop --user
		s.calls = append(s.calls, strings.Join(args, " "))
		switch args[0] {
		case "is-active":
			if s.active {
				return execx.Result{Stdout: "active\n"}, nil
			}
			return execx.Fail("systemctl", 3, "")
		case "is-enabled":
			if s.enabled {
				return execx.Result{Stdout: "enabled\n"}, nil
			}
			return execx.Fail("systemctl", 1, "")
		case "enable":
			s.enabled = true
		case "disable":
			s.enabled = false
		case "start":
			s.active = true
		case "stop":
			s.active = false
		}
	case "loginctl":
		switch c.Args[0] {
		case "show-user":
			if s.linger {
				return execx.Result{Stdout: "Linger=yes\n"}, nil
			}
			return execx.Result{Stdout: "Linger=no\n"}, nil
		case "enable-linger":
			if !s.lingerAllowed {
				return execx.Fail("loginctl", 1, "Interactive authentication required.")
			}
			s.linger = true
		}
	}
	return execx.Result{}, nil
}

func newPlatform(t *testing.T) (*Platform, *systemd, platform.Spec) {
	t.Helper()
	home := t.TempDir()
	sd := &systemd{lingerAllowed: true}
	p := &Platform{Exec: &execx.Fake{Handler: sd.handle}, User: "dev", Home: home}
	s := goldenSpec()
	s.Home = home
	return p, sd, s
}

func TestInstallEnablesLingerAndIsIdempotent(t *testing.T) {
	p, sd, s := newPlatform(t)
	if err := p.Install(ctx, s); err != nil {
		t.Fatal(err)
	}
	if !sd.enabled || !sd.linger || sd.active {
		t.Errorf("after Install: enabled=%v linger=%v active=%v, want enabled and lingering but not started", sd.enabled, sd.linger, sd.active)
	}
	if !strings.HasSuffix(p.DefinitionPath(s), "/.config/systemd/user/bladerunner-runner-build-box.service") {
		t.Errorf("unit path = %s", p.DefinitionPath(s))
	}
	if !reflect.DeepEqual(sd.calls[:2], []string{"daemon-reload", "is-enabled bladerunner-runner-build-box.service"}) {
		t.Errorf("calls = %v", sd.calls)
	}

	sd.calls = nil
	if err := p.Install(ctx, s); err != nil {
		t.Fatal(err)
	}
	for _, c := range sd.calls {
		if strings.HasPrefix(c, "daemon-reload") || strings.HasPrefix(c, "enable") {
			t.Errorf("re-Install of an unchanged unit issued %q", c)
		}
	}
}

func TestInstallTellsYouHowToEnableLingerWhenDenied(t *testing.T) {
	p, sd, s := newPlatform(t)
	sd.lingerAllowed = false
	err := p.Install(ctx, s)
	if diag.CodeOf(err) != diag.CodeServiceInstall || !strings.Contains(err.Error(), "sudo loginctl enable-linger dev") {
		t.Errorf("err = %v, want BR-E050 with the sudo command", err)
	}
	// The part that could be done is done: the next apply resumes at lingering.
	sd.lingerAllowed, sd.calls = true, nil
	if err := p.Install(ctx, s); err != nil || !sd.linger {
		t.Errorf("resumed Install: %v linger=%v", err, sd.linger)
	}
}

func TestStartStopStatusUninstall(t *testing.T) {
	p, sd, s := newPlatform(t)
	_ = p.Install(ctx, s)
	if st, _ := p.Status(ctx, s); !st.Installed || !st.Current || st.Running {
		t.Errorf("installed, stopped: %+v", st)
	}
	if err := p.Start(ctx, s); err != nil {
		t.Fatal(err)
	}
	if st, _ := p.Status(ctx, s); !st.Running || st.Detail != "systemd state: active" {
		t.Errorf("running: %+v", st)
	}
	if err := p.Stop(ctx, s); err != nil || sd.active {
		t.Errorf("Stop: %v active=%v", err, sd.active)
	}
	_ = p.Start(ctx, s)
	if err := p.Uninstall(ctx, s); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(p.DefinitionPath(s)); !os.IsNotExist(err) {
		t.Error("unit file still present")
	}
	if sd.active || sd.enabled {
		t.Errorf("after Uninstall: active=%v enabled=%v", sd.active, sd.enabled)
	}
	if err := p.Uninstall(ctx, s); err != nil {
		t.Errorf("Uninstall twice must succeed: %v", err)
	}
}

func TestStopOnAnUnknownUnitIsFine(t *testing.T) {
	p, _, s := newPlatform(t)
	p.Exec = &execx.Fake{Handler: func(c execx.Cmd) (execx.Result, error) {
		if c.Name == "systemctl" && c.Args[1] == "stop" {
			return execx.Fail("systemctl", 5, "Unit not loaded.")
		}
		if c.Name == "systemctl" && c.Args[1] == "is-active" {
			return execx.Fail("systemctl", 4, "")
		}
		return execx.Result{}, nil
	}}
	if err := p.Stop(ctx, s); err != nil {
		t.Errorf("Stop = %v, want nil for a unit that was never installed", err)
	}
}

func TestStartFailureNamesTheLogs(t *testing.T) {
	p, _, s := newPlatform(t)
	p.Exec = &execx.Fake{Handler: func(c execx.Cmd) (execx.Result, error) {
		return execx.Fail("systemctl", 1, "Failed to start: Unit not found.")
	}}
	err := p.Start(ctx, s)
	if diag.CodeOf(err) != diag.CodeServiceInstall || !strings.Contains(err.Error(), "bladerunner logs") {
		t.Errorf("err = %v", err)
	}
}

func TestPrereqs(t *testing.T) {
	sd := &systemd{}
	f := &execx.Fake{Tools: map[string]bool{"git": true, "systemctl": true, "loginctl": true}, Handler: sd.handle}
	for _, pr := range (&Platform{Exec: f}).CheckPrereqs(ctx) {
		if !pr.OK {
			t.Errorf("prereq %q should pass: %+v", pr.Name, pr)
		}
	}
	bad := &execx.Fake{Handler: func(c execx.Cmd) (execx.Result, error) { return execx.Fail(c.Name, 1, "Failed to connect to bus") }}
	got := map[string]platform.Prereq{}
	for _, pr := range (&Platform{Exec: bad}).CheckPrereqs(ctx) {
		got[pr.Name] = pr
	}
	for _, name := range []string{"git", "systemctl", "loginctl", "systemd user manager"} {
		if pr, ok := got[name]; !ok || pr.OK || pr.Fix == "" {
			t.Errorf("prereq %q on a bare machine = %+v", name, pr)
		}
	}
}

func TestLogsUsesJournalctl(t *testing.T) {
	p, _, s := newPlatform(t)
	f := &execx.Fake{Handler: func(execx.Cmd) (execx.Result, error) { return execx.Result{Stdout: "hello\n"}, nil }}
	p.Exec = f
	var out strings.Builder
	if err := p.Logs(ctx, s, false, &out); err != nil || out.String() != "hello\n" {
		t.Fatalf("Logs: %v %q", err, out.String())
	}
	if want := "[journalctl --user-unit bladerunner-runner-build-box.service -n 200 --no-pager]"; f.Line(0) != want {
		t.Errorf("command = %s", f.Line(0))
	}
}
